### ISSUE TITLE
Change ibovespa index datasource

### ISSUE THREAD

**Issue by joaopm33** [joaopm33/fundspy#10]
investpy (investing.com) only provides data for the index starting from 2008. CVM data starts in 2005.

Maybe theres a feasable ibovespa free source with data from earlier on.

**Comment by PPinh0** [comment]
You can get it from Yahoo Finance API. 

The identifier for iBovespa is ‘^BVSP’

**Comment by PPinh0** [comment]
Checked it out. Has data from 1993 up to today.

**Comment by joaopm33** [comment]
Thank you a lot Marcos, thats nice. The start_db and update_db functions will be adapted and I'll test them during the next days.

**Comment by joaopm33** [comment]
yahoo finance implemented as data source
